name: Nodejs Entity service test 

on:
  push:
    branches:
      - "entity_v2"
    paths-ignore:
      - "deploy/**"

env:
  SERVICE_DIRECTORY: "."
  SERVICE_DIRECTORY_FPA: "."
  ECR_REPO: "platform-solutions/test-arc"
  BRANCH: "entity_v2"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Application Code
        uses: docker://ghcr.io/kciter/aws-ecr-action:latest
        with:
          access_key_id: ${{ secrets.PLATFORM_AWS_ACCESS_KEY_PREPROD}}
          secret_access_key: ${{ secrets.PLATFORM_AWS_SECRET_KEY_PREPROD }}
          account_id: ${{ secrets.PLATFORM_AWS_ACCOUNT_ID_PREPROD }}
          repo: ${{ env.ECR_REPO }}
          region: ${{ secrets.PLATFORM_AWS_REGION_PREPROD }}
          create_repo: true
          set_repo_policy: false
          image_scanning_configuration: true
          tags: ${{ steps.version.outputs.app_version }}-dev-${{ needs.get-last-commit-id.outputs.commit_id }}
          dockerfile: ${{ env.SERVICE_DIRECTORY_FPA }}/Dockerfile
          extra_build_args: "--build-arg F_GITHUB_TOKEN=${{ secrets.CICD_KEY}} --build-arg F_REGISTRY=${{ secrets.PLATFORM_AWS_ACCOUNT_ID_PREPROD }}.dkr.ecr.${{ secrets.PLATFORM_AWS_REGION_PREPROD }}.amazonaws.com/platform-infra/"
          path: ${{ env.SERVICE_DIRECTORY_FPA }}