name: Nodejs Entity service test 

on:
  push:
    branches:
      - "entity_v2"
    paths-ignore:
      - "deploy/**"

env:
  SERVICE_DIRECTORY: "."
  ECR_REPO: "platform-solutions/test-arc"
  BRANCH: "entity_v2"

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get version
        id: version
        run: |
          version=$(jq -r .version $SERVICE_DIRECTORY/package.json )
          echo "::set-output name=app_version::${version}"
          commit_id=$(git rev-parse --short=7 HEAD)
          echo "::set-output name=commit::${commit_id}"
      - uses: docker://ghcr.io/kciter/aws-ecr-action:latest
        with:
          access_key_id: ${{ secrets.PLATFORM_AWS_ACCESS_KEY_preprod }}
          secret_access_key: ${{ secrets.PLATFORM_AWS_SECRET_KEY_preprod }}
          account_id: ${{ secrets.PLATFORM_AWS_ACCOUNT_ID_preprod }}
          repo:  ${{ env.ECR_REPO }}
          region: ${{ secrets.PLATFORM_AWS_REGION_preprod }}
          create_repo: true
          set_repo_policy: false
          image_scanning_configuration: true
          tags: ${{ steps.version.outputs.app_version }}-dev-${{ steps.version.outputs.commit }}
          dockerfile: ${{ env.SERVICE_DIRECTORY }}/Dockerfile
          extra_build_args: "--build-arg F_REGISTRY=${{ secrets.PLATFORM_AWS_ACCOUNT_ID_preprod }}.dkr.ecr.${{ secrets.PLATFORM_AWS_REGION_preprod }}.amazonaws.com/platform-infra/"
          path: ${{ env.SERVICE_DIRECTORY }}
      - name: Update Image version to auto-deploy
        uses: fjogeleit/yaml-update-action@v0.6.2
        with:
          valueFile: "deploy/deploy-values-dev.yaml"
          propertyPath: "apps.graphql-docs.image.version"
          value: ${{ steps.version.outputs.app_version }}-dev-${{ steps.version.outputs.commit }}
          branch: ${{ env.BRANCH }}
          message: "Update Image Version to ${{ steps.version.outputs.app_version }}-dev-${{ steps.version.outputs.commit }}"
          commitChange: "true"
          updateFile: "true"